# Generated by Django 5.0.2 on 2024-03-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='default.jpg', upload_to='photos/'),
        ),
    ]
