# Generated by Django 5.0.2 on 2024-03-10 23:57

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to=users.models.upload_path_profile_pic),
        ),
    ]
