# Generated by Django 5.0.2 on 2024-03-17 00:01

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='aaa.jpg', upload_to=users.models.upload_path_post_pic),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='aaa.jpg', upload_to=users.models.upload_path_profile_pic),
        ),
    ]
