# Generated by Django 5.0.2 on 2024-03-29 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_invitation_group_alter_message_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.group'),
        ),
    ]
